baseURL = "http://bim-us.org/"
languageCode = "en-us"
title = "Bible Institute of Missouri"
theme = "alpha-church"

themesDir = "themes"

rssLimit = 5

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Sermons"
    url = "/sermons"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Bible Institute of Missouri"
  subtitle = "The Bible Institute of Missouri is a work of the Kansas Expressway church of Christ, Sprinfield, Missouri."
  author = "Daniel Saunders"

  customCSS = ["example.css"]

  bible_popups = true

  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.map]
    # For Open Street Map widgets
    latitude = "37.2438206"
    longitude = "-93.3087143"
    zoom = "18"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "images/banner.jpg"

      [[params.landing.banner.button]]
        url = "/application"
        text = "Application"
        type = "special"

        [[params.landing.banner.button]]
        url = "#feature-icons"
        text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "Location"
      text = "[2540 N Kansas Expy, Springfield, MO 65803](https://goo.gl/maps/D9N1ar5ot1n)"
      map_location = "Bible Institute of Missouri"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = false

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-hands-helping"
        icon_pack = "fas"
        accent = "1"
        title = "Program"
        text = "The current preacher training program."

      [[params.landing.feature_icons.tile]]
        icon = "fa-church"
        icon_pack = "fas"
        accent = "2"
        title = "Faculty"
        text = "Meet the faculty."

      [[params.landing.feature_icons.tile]]
        icon = "fa-comments"
        icon_pack = "fas"
        accent = "5"
        title = "Resources"
        text = "Bible Institute resources."

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "3"
        title = "Alumni"
        text = "Current and past students."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/freely-10057.jpg"
        title = "Faculty"
        text = "The Bibile Insitute Faculty"
        url = "/faculty"
        button_text = "Meet"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Alumni"
        text = "Current and past students."
        url = "/alumni"
        button_text="Students"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Program"
        text = "The current preacher training program."
        url = "/program"
        button_text="Details"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Application"
        text = "Apply to become a student."
        url = "/application"
        button_text="Apply"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "https://www.facebook.com/bibleinstituteofmissouri/"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"

